server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/appdatabase?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    kafkaEventTopic: "statistic-topic"
    kafkaOrderGroupId: "kafka-booking-group-id"