spring:
  kafka:
    bootstrap-servers: localhost:9092
#  main:
#    allow-circular-references: true
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: postgres
    hikari:
      schema: app_schema
      connection-init-sql: create schema if not exists app_schema
      connection-timeout: 10000


app:
  kafka:
    kafkaBookingTopic: "booking-status-topic"
    kafkaRegisterTopic: "register-status-topic"
    kafkaOrderGroupId: "kafka-booking-group-id"
